/*
 * This file is generated by jOOQ.
 */
package org.ecommerce.infrastructure.jooq;


import java.util.Arrays;
import java.util.List;

import org.ecommerce.infrastructure.jooq.tables.Commodity;
import org.ecommerce.infrastructure.jooq.tables.Orders;
import org.ecommerce.infrastructure.jooq.tables.Promotion;
import org.ecommerce.infrastructure.jooq.tables.PromotionLog;
import org.ecommerce.infrastructure.jooq.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blackfriday extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blackfriday</code>
     */
    public static final Blackfriday BLACKFRIDAY = new Blackfriday();

    /**
     * The table <code>blackfriday.commodity</code>.
     */
    public final Commodity COMMODITY = Commodity.COMMODITY;

    /**
     * The table <code>blackfriday.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>blackfriday.promotion</code>.
     */
    public final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>blackfriday.promotion_log</code>.
     */
    public final PromotionLog PROMOTION_LOG = PromotionLog.PROMOTION_LOG;

    /**
     * The table <code>blackfriday.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Blackfriday() {
        super("blackfriday", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Commodity.COMMODITY,
            Orders.ORDERS,
            Promotion.PROMOTION,
            PromotionLog.PROMOTION_LOG,
            User.USER);
    }
}
