/*
 * This file is generated by jOOQ.
 */
package org.ecommerce.infrastructure.jooq;


import org.ecommerce.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in ecom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ecom.user</code>.
     */
    public static final User USER = User.USER;
}
