server:
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blackfriday?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    enabled: true
  spring:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 0
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    session.store-type: none
promotion:
  #  stock-strategy: sync
  #  stock-strategy: oversell
  stock-strategy: optimistic-lock
order:
  data-center: 1
  machine-num: 1
  delay-time: 60
rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group
    send-message-timeout: 7000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: false
    access-key:
    secret-key:
    enable-msg-trace: true
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC
  consumer:
    listeners:
      test-consumer-group:
        topic1: false